import React from 'react';
const Footer = () => {
    return (React.createElement(React.Fragment, null,
        React.createElement("footer", { className: "bg-stone-900 text-white py-8" },
            React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" },
                React.createElement("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-12" },
                    React.createElement("div", null,
                        React.createElement("h3", { className: "text-xl font-semibold mb-4" }, "About Us"),
                        React.createElement("p", { className: "text-gray-400" }, "We offer thrilling escape room experiences to challenge your mind and test your teamwork. Get ready to solve puzzles, uncover secrets, and escape before time runs out!")),
                    React.createElement("div", null,
                        React.createElement("h3", { className: "text-xl font-semibold mb-4" }, "Quick Links"),
                        React.createElement("ul", { className: "space-y-2" },
                            React.createElement("li", null,
                                React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white" }, "Home")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#rooms", className: "text-gray-400 hover:text-white" }, "Rooms")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#contact", className: "text-gray-400 hover:text-white" }, "Contact")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#faq", className: "text-gray-400 hover:text-white" }, "FAQ")))),
                    React.createElement("div", null,
                        React.createElement("h3", { className: "text-xl font-semibold mb-4" }, "Follow Us"),
                        React.createElement("div", { className: "flex space-x-6" },
                            React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white" },
                                React.createElement("svg", { className: "w-6 h-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true" },
                                    React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M3 12l2 2l2-2M5 6l2 2l2-2m2 12l2-2l2 2m2-12l2 2l2-2M3 18l2-2l2 2" }))),
                            React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white" },
                                React.createElement("svg", { className: "w-6 h-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true" },
                                    React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M19 12l-7 7l-7-7" }))),
                            React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white" },
                                React.createElement("svg", { className: "w-6 h-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true" },
                                    React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M3 5v14h18V5H3zm6 12l4-4l4 4V7l-4 4l-4-4v10z" }))))),
                    React.createElement("div", null,
                        React.createElement("h3", { className: "text-xl font-semibold mb-4" }, "Contact Us"),
                        React.createElement("p", { className: "text-gray-400" }, "Email: info@escaperoom.com"),
                        React.createElement("p", { className: "text-gray-400" }, "Phone: (123) 456-7890"),
                        React.createElement("p", { className: "text-gray-400" }, "Location: 123 Escape St, Mystery City"))),
                React.createElement("div", { className: "border-t border-gray-700 mt-12 pt-6 text-center" },
                    React.createElement("p", { className: "text-gray-400 text-sm" }, "\u00A9 2024 Escape Room, Inc. All rights reserved."))))));
};
export default Footer;
