import React from 'react';
const Nav = () => {
    return (React.createElement(React.Fragment, null,
        React.createElement("nav", { className: "bg-black text-white sticky top-0 z-50" },
            React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" },
                React.createElement("div", { className: "relative flex items-center justify-between h-16" },
                    React.createElement("div", { className: "absolute inset-y-0 left-0 flex items-center sm:hidden" },
                        React.createElement("button", { type: "button", className: "inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white", "aria-controls": "mobile-menu", "aria-expanded": "false" },
                            React.createElement("span", { className: "sr-only" }, "Open main menu"),
                            React.createElement("svg", { className: "block h-6 w-6", xmlns: "http://www.w3.org/2000/svg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true" },
                                React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16M4 18h16" })))),
                    React.createElement("div", { className: "flex-1 flex items-center justify-center sm:items-stretch sm:justify-start" },
                        React.createElement("div", { className: "flex items-center" },
                            React.createElement("svg", { className: "h-6 w-6 text-white mr-2", xmlns: "http://www.w3.org/2000/svg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true" },
                                React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M12 17v2m-6 0v-6a6 6 0 0 1 12 0v6m-6-6V7a3 3 0 1 0-6 0v4" })),
                            React.createElement("div", { className: "text-2xl font-semibold" }, "Locked Out")),
                        React.createElement("div", { className: "hidden sm:block sm:ml-6" },
                            React.createElement("div", { className: "flex space-x-4" },
                                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" }, "Home"),
                                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" }, "About"),
                                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" }, "Services"),
                                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" }, "Contact"))))))),
        React.createElement("div", { className: "sm:hidden", id: "mobile-menu" },
            React.createElement("div", { className: "space-y-1 px-2 pt-2 pb-3" },
                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" }, "Home"),
                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" }, "About"),
                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" }, "Services"),
                React.createElement("a", { href: "#", className: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" }, "Contact")))));
};
export default Nav;
