import React from 'react';
const TryRoom = () => {
    return (React.createElement(React.Fragment, null,
        React.createElement("section", { className: "py-16 bg-stone-950" },
            React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("h2", { className: "text-3xl sm:text-4xl font-bold text-stone-100 mb-4" }, "Try Out a Room"),
                    React.createElement("p", { className: "text-lg sm:text-xl text-stone-200 max-w-3xl mx-auto" }, "Choose from our exciting escape rooms and test your skills. Each room offers a unique challenge designed to keep you on your toes.")),
                React.createElement("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12" },
                    React.createElement("div", { className: "bg-stone-800 rounded-lg shadow-lg overflow-hidden" },
                        React.createElement("img", { src: "https://via.placeholder.com/600x400", alt: "Room 1", className: "w-full h-48 object-cover" }),
                        React.createElement("div", { className: "p-6" },
                            React.createElement("h3", { className: "text-xl font-semibold text-stone-100 mb-2" }, "Mystery Mansion"),
                            React.createElement("p", { className: "text-stone-300 mb-4" }, "A haunted mansion filled with secrets, puzzles, and traps. Can you escape before the clock runs out?"),
                            React.createElement("div", { className: "flex justify-between text-sm text-gray-500" },
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Win Rate:"),
                                    " 75%"),
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Creator:"),
                                    " John Doe")),
                            React.createElement("div", { className: "mt-4 flex items-center justify-between" },
                                React.createElement("div", { className: "flex items-center text-gray-600" },
                                    React.createElement("strong", { className: "mr-1" }, "Difficulty:"),
                                    React.createElement("span", { className: "text-yellow-500" }, "\u2B50\u2B50\u2B50\u2B50")),
                                React.createElement("a", { href: "#", className: "text-red-600 hover:text-red-700 font-semibold" }, "Try Now")))),
                    React.createElement("div", { className: "bg-stone-800 rounded-lg shadow-lg overflow-hidden" },
                        React.createElement("img", { src: "https://via.placeholder.com/600x400", alt: "Room 2", className: "w-full h-48 object-cover" }),
                        React.createElement("div", { className: "p-6" },
                            React.createElement("h3", { className: "text-xl font-semibold text-stone-100 mb-2" }, "The Pirate's Treasure"),
                            React.createElement("p", { className: "text-stone-300 mb-4" }, "Find hidden treasure on a pirate ship! Solve puzzles and navigate through the ship\u2019s mysteries."),
                            React.createElement("div", { className: "flex justify-between text-sm text-gray-500" },
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Win Rate:"),
                                    " 65%"),
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Creator:"),
                                    " Jane Smith")),
                            React.createElement("div", { className: "mt-4 flex items-center justify-between" },
                                React.createElement("div", { className: "flex items-center text-gray-600" },
                                    React.createElement("strong", { className: "mr-1" }, "Difficulty:"),
                                    React.createElement("span", { className: "text-yellow-500" }, "\u2B50\u2B50\u2B50")),
                                React.createElement("a", { href: "#", className: "text-red-600 hover:text-red-700 font-semibold" }, "Try Now")))),
                    React.createElement("div", { className: "bg-stone-800 rounded-lg shadow-lg overflow-hidden" },
                        React.createElement("img", { src: "https://via.placeholder.com/600x400", alt: "Room 3", className: "w-full h-48 object-cover" }),
                        React.createElement("div", { className: "p-6" },
                            React.createElement("h3", { className: "text-xl font-semibold text-stone-100 mb-2" }, "Escape the Lab"),
                            React.createElement("p", { className: "text-stone-300 mb-4" }, "A high-tech laboratory with secrets to uncover. Solve complex puzzles and escape before time runs out."),
                            React.createElement("div", { className: "flex justify-between text-sm text-gray-500" },
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Win Rate:"),
                                    " 80%"),
                                React.createElement("div", null,
                                    React.createElement("strong", null, "Creator:"),
                                    " Mike Johnson")),
                            React.createElement("div", { className: "mt-4 flex items-center justify-between" },
                                React.createElement("div", { className: "flex items-center text-gray-600" },
                                    React.createElement("strong", { className: "mr-1" }, "Difficulty:"),
                                    React.createElement("span", { className: "text-yellow-500" }, "\u2B50\u2B50\u2B50\u2B50\u2B50")),
                                React.createElement("a", { href: "#", className: "text-red-600 hover:text-red-700 font-semibold" }, "Try Now")))))))));
};
export default TryRoom;
